# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: SqlAzureDacpacDeployment@1
  displayName: 'newtest'
  inputs:
    azureSubscription: 'Visual Studio Enterprise with MSDN(479d6672-b304-4afa-a843-3304eaaf24b0)'
    ServerName: 'tenantserver'
    DatabaseName: 'newtenant'
    SqlUsername: 'lmsv'
    SqlPassword: 'Cavalo2321'
    DacpacFile: 'C:\Users\Tomazinho Gato\Documents\SQL Server Management Studio\DAC Packages'