# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'


steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'hey'


- task: SqlAzureDacpacDeployment@1
  inputs:
    AuthenticationType: 'server'
    ServerName: 'tenantserver'
    DatabaseName: 'newtenant'
    SqlUsername: 'lmsv'
    SqlPassword: 'Cavalo2321'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    IpDetectionMethod: 'AutoDetect'

